[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "^4.0.1"
actix-files = "^0.6.0"
actix = "^0.13.0"
actix-rt = "^2.7.0"
serde = "^1.0.137"
